; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.18"

; Profiles

; projects[mm][type] = profile
; projects[mm][download][type] = git
; projects[mm][download][url] = "https://github.com/maustyle/coach-7.x-1.x-dev.git"  

projects[views_bulk_operations][version] = "3.1"
projects[views_bulk_operations][subdir] = "contrib"

projects[admin_menu][version] = "3.0-rc4"
projects[admin_menu][subdir] = "contrib"

projects[admin_views][version] = "1.1"
projects[admin_views][subdir] = "contrib"

projects[apps][version] = "1.0-beta7"
projects[apps][subdir] = "contrib"
projects[apps][patches][] = "http://drupal.org/files/1790902-check-last-modified-existing.patch"

projects[backup_migrate][version] = "2.7"
projects[backup_migrate][subdir] = "contrib"

projects[ctools][version] = "1.3"
projects[ctools][subdir] = "contrib"

projects[caption_filter][version] = "1.2"
projects[caption_filter][subdir] = "contrib"
projects[caption_filter][patches][] = "http://drupal.org/files/1432092-button-and-image.patch"

projects[coffee][version] = "2.0"
projects[coffee][subdir] = "contrib"

projects[context][version] = "3.0-beta6"
projects[context][subdir] = "contrib"

projects[facetapi][version] = "1.3"
projects[facetapi][subdir] = "contrib"

projects[date][version] = "2.6"
projects[date][subdir] = "contrib"

projects[defaultconfig][version] = "1.0-alpha9"
projects[defaultconfig][subdir] = "contrib"

projects[defaultcontent][version] = "1.0-alpha9"
projects[defaultcontent][subdir] = "contrib"
projects[defaultcontent][patches][] = "http://drupal.org/files/1757782-cannot-import-menu-hierarchy-8.patch"

projects[derivicon][version] = "1.0"
projects[derivicon][subdir] = "contrib"

projects[devel][version] = "1.3"
projects[devel][subdir] = "contrib"

projects[devel_themer][version] = "1.x-dev"
projects[devel_themer][subdir] = "contrib"

projects[diff][version] = "3.2"
projects[diff][subdir] = "contrib"

projects[entity][version] = "1.0"
projects[entity][subdir] = "contrib"

projects[entityreference][version] = "1.0"
projects[entityreference][subdir] = "contrib"

projects[fape][version] = "1.1"
projects[fape][subdir] = "contrib"

projects[features][version] = "2.0-beta2"
projects[features][subdir] = "contrib"

projects[field_group][version] = "1.1"
projects[field_group][subdir] = "contrib"

projects[fieldable_panels_panes][version] = "1.4+5-dev"
projects[fieldable_panels_panes][subdir] = "contrib"

projects[file_entity][version] = "2.0-unstable7+61-dev"
projects[file_entity][subdir] = "contrib"

projects[image_resize_filter][version] = "1.13"
projects[image_resize_filter][subdir] = "contrib"

projects[jquery_update][version] = "2.3"
projects[jquery_update][subdir] = "contrib"

projects[libraries][version] = "2.1"
projects[libraries][subdir] = "contrib"

projects[link][version] = "1.1"
projects[link][subdir] = "contrib"

projects[linkit][version] = "2.6"
projects[linkit][subdir] = "contrib"

projects[media][version] = "2.0-unstable7+38-dev"
projects[media][subdir] = "contrib"
projects[media][patches][] = "http://drupal.org/files/media-browser-enter-submit-frontpage-1319528-11.patch"

projects[] = "media_vimeo"
projects[media_youtube][version] = "2.0-rc2+0-dev"
projects[media_youtube][subdir] = "contrib"

projects[menu_block][version] = "2.3"
projects[menu_block][subdir] = "contrib"

projects[module_filter][version] = "1.7"
projects[module_filter][subdir] = "contrib"

projects[nodehierarchy][version] = "2.x-dev"
projects[nodehierarchy][subdir] = "contrib"

projects[panelizer][version] = "3.1"
projects[panelizer][subdir] = "contrib"

projects[panels][version] = "3.3+39-dev"
projects[panels][subdir] = "contrib"

projects[panels_breadcrumbs][version] = "2.0"
projects[panels_breadcrumbs][subdir] = "contrib"

projects[panopoly_admin][version] = "1.0-rc4"
projects[panopoly_admin][subdir] = "contrib"

projects[panopoly_core][version] = "1.0-rc4"
projects[panopoly_core][subdir] = "contrib"

projects[panopoly_images][version] = "1.0-rc4"
projects[panopoly_images][subdir] = "contrib"

projects[panopoly_magic][version] = "1.0-rc4"
projects[panopoly_magic][subdir] = "contrib"

projects[panopoly_pages][version] = "1.0-rc4"
projects[panopoly_pages][subdir] = "contrib"

projects[panopoly_search][version] = "1.0-rc4"
projects[panopoly_search][subdir] = "contrib"

projects[panopoly_theme][version] = "1.0-rc4"
projects[panopoly_theme][subdir] = "contrib"

projects[panopoly_users][version] = "1.0-rc4"
projects[panopoly_users][subdir] = "contrib"

projects[panopoly_widgets][version] = "1.0-rc4"
projects[panopoly_widgets][subdir] = "contrib"

projects[panopoly_wysiwyg][version] = "1.0-rc4"
projects[panopoly_wysiwyg][subdir] = "contrib"

projects[pathauto][version] = "1.2"
projects[pathauto][subdir] = "contrib"
projects[pathauto][patches][] = "http://drupal.org/files/936222-pathauto-persist.patch"

projects[pm_existing_pages][version] = "1.4"
projects[pm_existing_pages][subdir] = "contrib"

projects[search_api][version] = "1.4"
projects[search_api][subdir] = "contrib"

projects[search_api_db][version] = "1.0-beta4"
projects[search_api_db][subdir] = "contrib"

projects[search_api_solr][version] = "1.0-rc3"
projects[search_api_solr][subdir] = "contrib"
projects[search_api_solr][patches][] = "http://drupal.org/files/1407282-variable_solr_connection_class-37.patch"

projects[simple_gmap][version] = "1.0"
projects[simple_gmap][subdir] = "contrib"

projects[simplehtmldom][version] = "1.12"
projects[simplehtmldom][subdir] = "contrib"

projects[skinr][version] = "2.0-beta1"
projects[skinr][subdir] = "contrib"

projects[strongarm][version] = "2.0"
projects[strongarm][subdir] = "contrib"

projects[tablefield][version] = "2.1"
projects[tablefield][subdir] = "contrib"

projects[token][version] = "1.5"
projects[token][subdir] = "contrib"

projects[uuid][version] = "1.0-alpha3+47-dev"
projects[uuid][subdir] = "contrib"
projects[uuid][patches][] = "http://drupal.org/files/1605284-define-types-for-tokens-6.patch"

projects[views][version] = "3.7"
projects[views][subdir] = "contrib"

projects[views_autocomplete_filters][version] = "1.0-beta2"
projects[views_autocomplete_filters][subdir] = "contrib"

projects[wysiwyg][version] = "2.2"
projects[wysiwyg][subdir] = "contrib"
projects[wysiwyg][patches][] = "http://drupal.org/files/wysiwyg-arbitrary_image_paths_markitup-1786732-3.patch"

projects[wysiwyg_filter][version] = "1.6-rc2"
projects[wysiwyg_filter][subdir] = "contrib"

; Themes
projects[abstract][version] = "1.0-unstable1"
projects[abstract][subdir] = "contrib"

projects[acquia_prosper][version] = "1.x-dev"
projects[acquia_prosper][subdir] = "contrib"

projects[fusion][version] = "2.0-beta2"
projects[fusion][subdir] = "contrib"

projects[kalatheme][version] = "1.0"
projects[kalatheme][subdir] = "contrib"

projects[kanji][version] = "3.5"
projects[kanji][subdir] = "contrib"

projects[openasu_bootstrap][type] = "theme"
projects[openasu_bootstrap][subdir] = "contrib"
projects[openasu_bootstrap][download][type] = "git"
projects[openasu_bootstrap][download][url] = "https://github.com/kalamuna/openasu_bootstrap.git"

projects[radix][version] = "2.0-alpha3+7-dev"
projects[radix][subdir] = "contrib"

projects[responsive_bartik][version] = "1.0-beta1+3-dev"
projects[responsive_bartik][subdir] = "contrib"
projects[responsive_bartik][patches][] = "http://drupal.org/files/1966198-remove-auto-width.patch"

projects[sizzle][version] = "1.x-dev"
projects[sizzle][subdir] = "contrib"

; Libraries

libraries[bootstrap][download][type] = "get"
libraries[bootstrap][download][url] = "https://github.com/kalamuna/asu_bootlibrary/archive/v2.3.0.zip"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
; libraries[markitup][download][type] = ""
; libraries[markitup][download][url] = ""
; libraries[markitup][directory_name] = "markitup"
; libraries[markitup][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
; libraries[respondjs][download][type] = ""
; libraries[respondjs][download][url] = ""
; libraries[respondjs][directory_name] = "respondjs"
; libraries[respondjs][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
; libraries[SolrPhpClient][download][type] = ""
; libraries[SolrPhpClient][download][url] = ""
; libraries[SolrPhpClient][directory_name] = "SolrPhpClient"
; libraries[SolrPhpClient][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
libraries[superfish][download][type] = "get"
libraries[superfish][download][url] = "https://github.com/mehrpadin/Superfish-for-Drupal/archive/1.x.zip"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
; libraries[tinymce][download][type] = ""
; libraries[tinymce][download][url] = ""
; libraries[tinymce][directory_name] = "tinymce"
; libraries[tinymce][type] = "library"

